### PR TITLE
Fix http trace not sent if connection is keep-alive

### PR DESCRIPTION
**Pull request by aunsy-com**
Closes https://github.com/apache/skywalking/issues/11583

### CODE REVIEW

**Comment by tkNobug** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Review by kezhenxu94 — APPROVED** [review]

**Comment by kezhenxu94** [comment]
@aunsy-com the tests failed, can you take a look?

**Comment by aunsy-com** [comment]
> @aunsy-com the tests failed, can you take a look?

from the error log, it looks like the env start error, then the test case execute failed
image

**Comment by wu-sheng** [comment]
We seem not to set up required CI and sync with latest target branch

**Comment by aunsy-com** [comment]
> @aunsy-com thank you!

It's my pleasure, and thank you for your team work.

**Pull request merged**
