### PR TITLE
Add mysql2 plugin 

### PR DESCRIPTION
**Pull request by tianyk**
Add [mysql2](https://www.npmjs.com/package/mysql2) plugin

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Test failed. Please recheck.

**Comment by tianyk** [comment]
Please review.

**Review by kezhenxu94 — APPROVED** [review]
LGTM, @tom-pytel can you please do another round review?

**Comment by zyfyuanyuan6** [comment]
@kezhenxu94  when i start local server， it will throw an error 'Error installing plugin mysql 2 *',  i used version 3.0

**Comment by wu-sheng** [comment]
> @kezhenxu94 when i start local server， it will throw an error 'Error installing plugin mysql 2 *', i used version 3.0

Isn't this a mysql2 plugin?

**Comment by riskgod** [comment]
> > @kezhenxu94 when i start local server， it will throw an error 'Error installing plugin mysql 2 *', i used version 3.0
> 
> Isn't this a mysql2 plugin?

Yep, our team met this err in the same version.

**Comment by wu-sheng** [comment]
There is no 3.0, I don't know what do you mean? 

https://www.npmjs.com/package/mysql2 2.2.5 is the latest release.

**Comment by zyfyuanyuan6** [comment]
> There is no 3.0, I don't know what do you mean?
> 
> https://www.npmjs.com/package/mysql2 2.2.5 is the latest release.

sorry i mean skywalking-nodejs version.

**Comment by zyfyuanyuan6** [comment]
> > > @kezhenxu94 when i start local server， it will throw an error 'Error installing plugin mysql 2 *', i used version 3.0
> > 
> > 
> > Isn't this a mysql2 plugin?
> 
> Yep, our team met this err in the same version.

i want to know how can solve it when you meet?

**Comment by wu-sheng** [comment]
> > > > @kezhenxu94 when i start local server， it will throw an error 'Error installing plugin mysql 2 *', i used version 0.3.0
> 
> > > 
> 
> > > 
> 
> > > Isn't this a mysql2 plugin?
> 
> > 
> 
> > Yep, our team met this err in the same version.
> 
> 
> 
> i want to know how can solve it when you meet?

This is open source project, you simply debug directly. I don't know what do you mean.

**Comment by riskgod** [comment]
> version

Still not find the solution, But we can do something in https://github.com/apache/skywalking-nodejs/blob/master/src/core/PluginInstaller.ts#L48

**Comment by riskgod** [comment]
> > > > > @kezhenxu94 when i start local server， it will throw an error 'Error installing plugin mysql 2 *', i used version 0.3.0
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Isn't this a mysql2 plugin?
> > 
> > 
> > > 
> > 
> > 
> > > Yep, our team met this err in the same version.
> > 
> > 
> > i want to know how can solve it when you meet?
> 
> This is open source project, you simply debug directly. I don't know what do you mean.

Yep, try to solve it, but the problem is existed, we need to fix it together.

**Comment by kezhenxu94** [comment]
@riskgod can you print the error in https://github.com/apache/skywalking-nodejs/blob/babf6ebc0022909ef1bb865764045c7ce62c3b1c/src/core/PluginInstaller.ts#L109 in your local env to see what's the error?

**Comment by riskgod** [comment]
> @riskgod can you print the error in
> 
> https://github.com/apache/skywalking-nodejs/blob/babf6ebc0022909ef1bb865764045c7ce62c3b1c/src/core/PluginInstaller.ts#L109
> 
> in your local env to see what's the error?

'Error installing plugin mysql 2 *'

**Comment by kezhenxu94** [comment]
I think you don't understand how to report a potential bug in an open source project and how to help the maintainer to locate it, only providing a error message helps nothing, you don't have a reproducible demo project, nor did you show the Efforts you've made to debug the problem, we are powerless to waste our time to debug this problem as we don't even know whether it's a bug or not because you gave no useful reproducible steps. This plugin is run in our tests with a typical scenario and it passed, if your scenario is different with it you have to provide your scenario in more details, otherwise we are not able to do anything.

We've been asking for more details but you always paste the same error logs, this is a waste of time and useless communication.

> > @riskgod can you print the error in
> > https://github.com/apache/skywalking-nodejs/blob/babf6ebc0022909ef1bb865764045c7ce62c3b1c/src/core/PluginInstaller.ts#L109
> > 
> > in your local env to see what's the error?
> 
> 'Error installing plugin mysql 2 *'

If you still want to help, try to print the `e` 

https://github.com/apache/skywalking-nodejs/blob/babf6ebc0022909ef1bb865764045c7ce62c3b1c/src/core/PluginInstaller.ts#L107-L113

Something like this 

```typescript
      } catch (e) {
        if (plugin) {
          logger.error(`Error installing plugin ${plugin.module} ${plugin.versions}`, e); // <<===== 👈
        } else {
          logger.error(`Error processing plugin ${pluginFile}`);
        }
      }
```

... to see why the plugin is not installed successfully.

**Comment by riskgod** [comment]
> I think you don't understand how to report a potential bug in an open source project and how to help the maintainer to locate it, only providing a error message helps nothing, you don't have a reproducible demo project, nor did you show the Efforts you've made to debug the problem, we are powerless to waste our time to debug this problem as we don't even know whether it's a bug or not because you gave no useful reproducible steps. This plugin is run in our tests with a typical scenario and it passed, if your scenario is different with it you have to provide your scenario in more details, otherwise we are not able to do anything.
> 
> We've been asking for more details but you always paste the same error logs, this is a waste of time and useless communication.
> 
> > > @riskgod can you print the error in
> > > https://github.com/apache/skywalking-nodejs/blob/babf6ebc0022909ef1bb865764045c7ce62c3b1c/src/core/PluginInstaller.ts#L109
> > > 
> > > in your local env to see what's the error?
> > 
> > 
> > 'Error installing plugin mysql 2 *'
> 
> If you still want to help, try to print the `e`
> 
> https://github.com/apache/skywalking-nodejs/blob/babf6ebc0022909ef1bb865764045c7ce62c3b1c/src/core/PluginInstaller.ts#L107-L113
> 
> Something like this
> 
> ```ts
>       } catch (e) {
>         if (plugin) {
>           logger.error(`Error installing plugin ${plugin.module} ${plugin.versions}`, e); // <<===== 👈
>         } else {
>           logger.error(`Error processing plugin ${pluginFile}`);
>         }
>       }
> ```
> 
> ... to see why the plugin is not installed successfully.

yep, found the problem. the mysql2 plugin use exports in package.json. not export commonjs in [here](https://github.com/sidorares/node-mysql2/blob/master/package.json#L46), like this: `".": "./index.cjs"`, still try to fix this is in this npm module. Don't worry, I will try to covert that

**Pull request merged**
