### PR TITLE
fix: add namespace for trace id prefix

### PR DESCRIPTION
**Pull request by wuliupo**

### CODE REVIEW

**Comment by wu-sheng** [comment]
`sw8` is the required key in the API. This PR can't be accepted.

**Comment by tkNobug** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wu-sheng** [comment]
I believe we had removed that from Java agent long time ago. Maybe you looked at old blogs?

**Comment by wu-sheng** [comment]
That was a long time ago decision as it is easy to break other integration. Not every place adopted this, and it's not widely used.

**Comment by zhaoxiaojie0415** [comment]
> That was a long time ago decision as it is easy to break other integration. Not every place adopted this, and it's not widely used.

Got it, thanks

**Pull request closed without merging**
