### PR TITLE
Upgrade dependencies to fix vulnerabilities

### PR DESCRIPTION
**Pull request by ruleeeer**
This PR is to fix a vulnerability that occurs when using npm install, as follows

image

### CODE REVIEW

**Comment by ruleeeer** [comment]
In addition, I would like to know how to participate in the contribution to skywalking and is there any relevant literature or blogs that I can refer to understand the operation mechanism of skywalking, I can contribute using js/ts and java

**Comment by kezhenxu94** [comment]
> In addition, I would like to know how to participate in the contribution to skywalking and is there any relevant literature or blogs that I can refer to understand the operation mechanism of skywalking, I can contribute using js/ts and java

All materials of skywalking is public for globally access, for tasks open to new contributors please refer to our GitHub issues https://github.com/apache/skywalking/issues

**Comment by kezhenxu94** [comment]
> > In addition, I would like to know how to participate in the contribution to skywalking and is there any relevant literature or blogs that I can refer to understand the operation mechanism of skywalking, I can contribute using js/ts and java
> 
> All materials of skywalking is public for globally access, for tasks open to new contributors please refer to our GitHub issues https://github.com/apache/skywalking/issues

For most (new) contributors they usually got started by contributing plugins to the SkyWalking agent of their favorite languages and favorite(familiar) libraries/modules/frameworks.

**Comment by kezhenxu94** [comment]
I'd say it's also pretty nice that you get yourself familiar with the contributing process (how to open a PR and get review comments from reviewers, modify PR content accordingly, make the CI passed, etc.), if you like you can start to dig deep in the real content of this NodeJS agent and try to contribute a plugin of a module that you're most familiar with.

**Comment by ruleeeer** [comment]
Thanks for the advice, let me start with nodejs

**Comment by kezhenxu94** [comment]
> Thanks for the advice, let me start with nodejs

Take a look at this https://github.com/apache/skywalking/issues?q=is%3Aopen+is%3Aissue+label%3Anodejs we have good first issues labeled with `NodeJS` for contributors like you

**Review by kezhenxu94 — APPROVED** [review]
Looks nice!! 0 vulnerabilities now

**Pull request merged**
